# muuta seuraavaan kohtaan oman projektisi id
# Käytä vain pieniä kirjaimia ja numeroita
# projektin nimi ei saa alkaa numerolla
application: jaankaup-tiea2080-harjoitus7
runtime: python27
api_version: 1
version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
